language: go
sudo: false

go:
  - 1.5


services:
  - redis-server
  - mongodb

install:
  - go get -d -v ./...
  - go build -v ./...
  - go get golang.org/x/tools/cover


secure: "F3GrvKUQkuIJyzamGM3fw5tTZfYtSCmR+02t5KpqsqkBt1iBM2w4wlZjm+kMzisz8NDVZYfXYDYIqLhfBa4kwSPGgUqxqXAsMhI7hEco3P2FZ6nre0HC0QYhvKks07644KsVq1J2Xn7JMT+61rXKeEk4Ncu1spZCfWbhiJk+MKA="

script:
  - go test -tags 'coprocess' -v -covermode=count -coverprofile=coverage.out
